# Jekyll configuration file

# site settings
title: Julien Seguinot
description: Glaciers, Python and open-source.
url: https://juseg.github.io

# theme settings
tagline: Personal webpage.
navigation:
  - {name: 'About', link: '/about'}
  - {name: 'Blog', link: '/blog'}
  - {name: 'Outreach', link: '/outreach'}
  - {name: 'Publications', link: '/publications'}
  - {name: 'Contact', link: '/contact'}
github_username: juseg

# build settings
remote_theme: juseg/keels
permalink: /:title/
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - vendor

# jekyll plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
